### ISSUE TITLE
[DESIGN] Logo

### ISSUE THREAD

**Issue by fdaciuk** [lukinco/adonis-apollo-server#2]
If you are a designer, and want to suggest a logo for this project, be my guest :)

**Comment by mandyellow** [comment]
Hello! I made a logo for your project. Let me know if you like it. 🦊

Primary and negative version:
![image](https://user-images.githubusercontent.com/30158643/95631736-9189e580-0a5a-11eb-833a-2ca22677a0d7.png)

**Comment by fdaciuk** [comment]
That's amazing @mandyellow! I loved it! :D
Can you send a PR? Thank you so much ❤️

**Comment by mandyellow** [comment]
Yay! Where can I upload the logo? Maybe in 'src'?

SVG and PNG are ok for you? Or do you need another extension?

**Comment by fdaciuk** [comment]
You can create a directory called `design` on the root path of this project :)
Yes, SVG and PNG are perfect! Thanks again 😁
