### ISSUE TITLE
[pt-BR] Tradução da documentação

### ISSUE THREAD

**Issue by fdaciuk** [lukinco/adonis-apollo-server#3]
Precisamos traduzir a documentação do `adonis-apollo-server` para Português do Brasil.

As discussões gerais desse projeto deverão ser em inglês, mas essa issue, especificamente, pode ser discutida em português, já que tem relação com a tradução da documentação para pt-BR.

Se você gostaria de trabalhar nessa issue, sinalize aqui na issue, e vamos discutindo os detalhes de como deve ser feita essa tradução, ok? :)

**Comment by adeonir** [comment]
@fdaciuk vou fazer essa tradução o/

**Comment by fdaciuk** [comment]
Boa @adeonir! Se quiser, pode seguir o padrão feito [nesse projeto](https://github.com/fdaciuk/hmh) :)
